title: mstfa cmly - Game Designer
description: Personal website & résumé for mstfa cmly
url: https://www.mstfacmly.com
author: mstfa cmly
birthday: '1984-04-11 00:00:00 +0300'
langs: العربية, English, French, a little bit of Spanish and Italian
proglangs: Python, GDScript & Web languages (HTML, CSS, Markdown, Liquid)

#contact info
email: mstfacmly@studioslune.com
twitter: "@mstfacmly"
github:
        user: mstfacmly
        repo: github.com/mstfacmly
gravatar: 053189a14b858da5286971d47897ca68
steam: mstfacmly
discord: mstfacmly#1855

#remote-theme: fongandrew/hydeout
permalink: pretty #/blog/:year/:month/:day/:title
markdown: kramdown
plugins:
        - jekyll-sitemap
