name: mstfa cmly - Game Designer
description: Personal website & résumé for mstfa cmly
author: mstfa cmly
birthday: '1984-04-11 00:00:00 +500'

#contact info
email: mstfacmly@studioslune.com
twitter: "@mstfacmly"
github:
        user: mstfacmly
        repo: github.com/mstfacmly

#remote-theme: fongandrew/hydeout
permalink: pretty #/blog/:year/:month/:day/:title
markdown: kramdown
plugins:
        - jekyll-sitemap
