title: mstfa cmly - Game Designer
description: Personal website & résumé for mstfa cmly
url: https://mstfacmly.com
author: mstfa cmly
birthday: '1984-04-11 00:00:00 +0300'
langs: العربية, English, French, a little bit of Spanish and Italian
proglangs: Python, GDScript, & Web languages (HTML, CSS, Markdown, Liquid)
OS: Ubuntu 18.04
OSsite: https://ubuntu.com
phoneOS: Android Oreo
phoneOSsite: https://www.android.com/versions/oreo-8-0/

#contact info
email: mstfacmly@studioslune.com
twitter: "@mstfacmly"
github:
        user: mstfacmly
        repo: https://github.com/mstfacmly
gravatar: 053189a14b858da5286971d47897ca68
medium: https://medium.com/@mstfacmly
steam: mstfacmly
discord: mstfacmly#1855
rss: atom.xml

#remote-theme: fongandrew/hydeout
permalink: pretty #/blog/:year/:month/:day/:title
markdown: kramdown
plugins:
        - jekyll-sitemap
        - jekyll-hinduarabic
        - jekyll-github-metadata
        - jekyll-gallery-generator
        - hijri
